apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-py
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-py
  template:
    metadata:
      labels:
        app: weather-py
    spec:
      containers:
      - name: weather-py
        image: brainupgrade/weather-py
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: weather-py-service
spec:
  type: NodePort
  selector:
    app: weather-py
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      # NodePort field is optional. If not specified, Kubernetes will allocate a port automatically.
      # nodePort: 30007
